services:
  repair:
    build:
      context: ..
      dockerfile: postgres-data-handler-repair/Dockerfile.repair
    env_file:
      - ./data-handler.env
    volumes:
      # Use the same volume name as your backend docker-compose.yml
      - backend_db_volume:/db:ro
    restart: "no"

volumes:
  backend_db_volume:
    external: true
    name: run_mainnet-db
