services:
  repair:
    build:
      context: ..
      dockerfile: postgres-data-handler-repair/Dockerfile.repair
    env_file:
      - ./data-handler.env
    environment:
      - NODE_URL=http://backend:17001
      - STATE_CHANGE_DIR=/db/state-changes
      - REPAIR_WORKERS=200
      # Smart reprocessing options (uncomment to use)
      # - USE_STATE_CHANGES=true
      # - SKIP_BLOCKS=true
      # - REPAIR_START_HEIGHT=8606270
      # - REPAIR_END_HEIGHT=8606370
      # Or use gap file
      # - GAP_FILE=state-changes-gaps.txt
    volumes:
      # Use the same bind mount as your backend container
      - /opt/volumes/backend:/db:ro
    restart: "no"
    networks:
      - run_internal

networks:
  run_internal:
    external: true
