services:
  repair:
    build:
      context: ..
      dockerfile: postgres-data-handler-repair/Dockerfile.repair
    env_file:
      - ./data-handler.env
    environment:
      - NODE_URL=http://backend:17001
    volumes:
      # Use the same bind mount as your backend container
      - /opt/volumes/backend:/db:ro
    restart: "no"
    networks:
      - run_default

networks:
  run_default:
    external: true
