services:
  reprocess-blocks:
    build:
      context: ..
      dockerfile: postgres-data-handler/Dockerfile.reprocess-blocks
    env_file:
      - ./data-handler.env
    environment:
      - DATA_HANDLER_ENV=./data-handler.env
    volumes:
      - ./blocks-reprocess.txt:/postgres-data-handler/src/postgres-data-handler/blocks-reprocess.txt:ro
      - ./data-handler.env:/postgres-data-handler/src/postgres-data-handler/data-handler.env:ro
    restart: "no"
    networks:
      - run_internal

networks:
  run_internal:
    external: true
